import Chat from "@/components/chatboat/Chat";
import "./globals.css";
import ProvidersToast from "@/components/layout/Providers";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "XRP-Boys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersToast>
          <ReduxProvider>
            {children}
            {/* <Chat /> */}
          </ReduxProvider>
        </ProvidersToast>
      </body>
    </html>
  );
}
