import {
  HeartHandshake,
  ShoppingCart,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Twitter,
  Forward,
  FileText,
  Youtube,
  Instagram,
  Search,
  Image,
  Layers,
  Banknote,
  KeyRound,
  Wallet,
  User,
  Gauge,
  Heart,
  ListTodo,
  FileBarChart,
  LayoutList,
  Bell,
  Plus,
  Flag,
  AlignRight,
  Eye,
  X,
  Minus,
  ListFilter,
  Grid,
  LayoutGrid,
  Hexagon,
  FileBadge2,
  FileSpreadsheet,
  CircleDot,
  LineChart,
  LayoutListIcon,
  LayoutPanelLeft,
  Unlock,
  XIcon,

  Trash2,
  AlertOctagon,
  Box,
  Loader2,
  PenLine,
  type Icon as LucideIcon,
  type LucideProps,
} from "lucide-react";
import { RiLogoutCircleLine } from "react-icons/ri";
import { FaDiscord, FaTiktok } from "react-icons/fa";
import { SlSocialReddit } from "react-icons/sl";
import { FcGoogle } from "react-icons/fc";

export type Icon = LucideIcon;

export const Icons = {
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  dashboard: Gauge,
  x: XIcon,
  collection: Layers,
  nft: Image,
  trash2: Trash2,
  circleDot: CircleDot,
  lineChart: LineChart,
  fileSpreadsheet: FileSpreadsheet,
  fileBadge2: FileBadge2,
  eye: Eye,
  hexagon: Hexagon,
  fileBarChart: FileBarChart,
  fileText: FileText,
  nft_offers: ListTodo,
  favorites: Heart,
  purchase: Banknote,
  profile: User,
  share: Forward,
  handshake: HeartHandshake,
  wallet: Wallet,
  notifications: Bell,
  search: Search,
  twitter: Twitter,
  youtube: Youtube,
  instagram: Instagram,
  shoppingCart: ShoppingCart,
  offers: LayoutList,
  add: Plus,
  report: Flag,
  options: AlignRight,
  key: KeyRound,
  X: X,
  minus: Minus,
  filter: ListFilter,
  grid: Grid,
  layoutGrid: LayoutGrid,
  layoutList: LayoutListIcon,
  layoutPanelLeft: LayoutPanelLeft,
  unlock: Unlock,
  alert: AlertOctagon,
  box: Box,
  edit: PenLine,
  loader: Loader2,
  logout: ({ ...props }: LucideProps) => <RiLogoutCircleLine {...props} />,
  discord: ({ ...props }: LucideProps) => <FaDiscord {...props} />,
  tiktok: ({ ...props }: LucideProps) => <FaTiktok {...props} />,
  reddit: ({ ...props }: LucideProps) => <SlSocialReddit {...props} />,
  google: ({ ...props }: LucideProps) => <FcGoogle {...props} />,
};
